aws_region                            = "us-east-1"
iam_role_name                         = "lambda_execution_role"
cw_event_rule_name                    = "lambda_cron_event_rule"
lambda_function_name                  = "cron_lambda_function"
iam_policy_name                       = "lambda_permissions_policy"
s3_bucket_name                        = "project-cron-lambda-s3-bucket"
s3_bucket_versioning_status           = "Disabled"
kms_key_deletion_window_in_days       = 10
# bucket_object_lock_configuration_days = 5
