name: Terraform AWS Cron Lambda Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'

jobs:
  terraform:
    name: Terraform Lambda Build Workflow
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: /home/runner/work/uc-d4cg-project/uc-d4cg-project/terraform
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.TF_STATE_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var-file=./configurations/lambda-deploy.tfvars \
            -out=${{ env.TF_WORKING_DIR }}/lambda-deploy.tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
